server:
  port: 8081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.120.80:8040
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always